### ISSUE TITLE
Windows 11 failing to load bootcode4.bin

### ISSUE THREAD

**Issue by RassK** [raspberrypi/usbboot#182] opened 2023-05-11 11:23 UTC
### Describe the bug

I know that the doc recommends Windows 10 PC, but just in case reporting that Windows 11 PC fails to mount the eMMC drive.
Attached to different PC with native Windows 10, everything works on the first try. 

Detected 3 different behaviours:
1. Keeps looping `Loading: .\msd/bootcode4.bin`
2. Keeps failing to send bootcode (#36)
3. Windows keeps reporting usb device malfunctioned in every single usb port I have.

### Steps to reproduce the behaviour

Run:
`rpiboot -d .\msd`

### Device(s)

Raspberry Pi CM4

### Compute Module IO board.

Turing PI 2

### Kernel logs

```
Device USB\VID_0000&PID_0003\9&1fba9631&0&4 was configured.

Driver Name: usb.inf
Class Guid: {36fc9e60-c465-11cf-8056-444553540000}
Driver Date: 06/21/2006
Driver Version: 10.0.22621.1194
Driver Provider: Microsoft
Driver Section: BADDEVICE.Dev.NT
Driver Rank: 0xFF0000
Matching Device Id: USB\CONFIG_DESCRIPTOR_FAILURE
Outranked Drivers: usb.inf:USB\CONFIG_DESCRIPTOR_FAILURE:00FF2000
Device Updated: false
Parent Device: USB\VID_05E3&PID_0608\8&2efe0359&0&6
```
```
Device USB\VID_0000&PID_0003\9&1fba9631&0&4 had a problem starting.

Driver Name: usb.inf
Class Guid: {36fc9e60-c465-11cf-8056-444553540000}
Service: 
Lower Filters: 
Upper Filters: 
Problem: 0x0
Problem Status: 0xC00000E5
```

**Comment by timg236** [comment] 2023-05-11 12:20
This appears to be a duplicate of the linked bug - there's no official support for Windows but happy to merge in PRs

**Closed as completed** 2024-01-08 13:54 UTC

**Comment by JmartinezCID** [comment] 2024-04-23 17:10
when i encountered this issue the only thing i found that rectified it was removing anything from the usb ports on my computer. in my instance it was a wireless mouse dongle that i disconnected. nothing else connected to the pc but the medium for the cm4 to the pc.
